<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260709124054 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE account_users (id UUID NOT NULL, role VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_220C7C989B6B5FBA ON account_users (account_id)');
        $this->addSql('CREATE INDEX IDX_220C7C98A76ED395 ON account_users (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_account_user ON account_users (account_id, user_id)');
        $this->addSql('CREATE TABLE accounts (id UUID NOT NULL, label VARCHAR(120) NOT NULL, type VARCHAR(20) NOT NULL, currency VARCHAR(3) NOT NULL, iban VARCHAR(34) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CAC89EACB03A8386 ON accounts (created_by_id)');
        $this->addSql('CREATE TABLE audit_logs (id UUID NOT NULL, user_id UUID DEFAULT NULL, action VARCHAR(100) NOT NULL, entity VARCHAR(100) DEFAULT NULL, entity_id UUID DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, context JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_user ON audit_logs (user_id)');
        $this->addSql('CREATE INDEX idx_audit_action ON audit_logs (action)');
        $this->addSql('CREATE TABLE budgets (id UUID NOT NULL, month VARCHAR(7) NOT NULL, amount NUMERIC(14, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id UUID NOT NULL, category_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DCAA95489B6B5FBA ON budgets (account_id)');
        $this->addSql('CREATE INDEX IDX_DCAA954812469DE2 ON budgets (category_id)');
        $this->addSql('CREATE INDEX idx_budget_account_month ON budgets (account_id, month)');
        $this->addSql('CREATE UNIQUE INDEX budget_unique ON budgets (account_id, category_id, month)');
        $this->addSql('CREATE TABLE categories (id UUID NOT NULL, name VARCHAR(80) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parent_id UUID DEFAULT NULL, owner_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AF34668727ACA70 ON categories (parent_id)');
        $this->addSql('CREATE INDEX IDX_3AF346687E3C61F9 ON categories (owner_id)');
        $this->addSql('CREATE TABLE invitations (id UUID NOT NULL, email VARCHAR(180) NOT NULL, role VARCHAR(20) NOT NULL, token_hash VARCHAR(64) NOT NULL, status VARCHAR(20) NOT NULL, invited_by UUID NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_232710AE9B6B5FBA ON invitations (account_id)');
        $this->addSql('CREATE INDEX idx_invitation_hash ON invitations (token_hash)');
        $this->addSql('CREATE TABLE one_time_tokens (id UUID NOT NULL, user_id UUID NOT NULL, type VARCHAR(30) NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_ott_hash ON one_time_tokens (token_hash)');
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE transactions (id UUID NOT NULL, date DATE NOT NULL, amount NUMERIC(14, 2) NOT NULL, label VARCHAR(180) NOT NULL, attachment_url VARCHAR(500) DEFAULT NULL, created_by UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id UUID NOT NULL, category_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EAA81A4C9B6B5FBA ON transactions (account_id)');
        $this->addSql('CREATE INDEX IDX_EAA81A4C12469DE2 ON transactions (category_id)');
        $this->addSql('CREATE INDEX idx_tx_account_date ON transactions (account_id, date)');
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, google_id VARCHAR(255) DEFAULT NULL, totp_secret VARCHAR(255) DEFAULT NULL, totp_enabled BOOLEAN NOT NULL, banned BOOLEAN NOT NULL, password_changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON users (email)');
        $this->addSql('ALTER TABLE account_users ADD CONSTRAINT FK_220C7C989B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE account_users ADD CONSTRAINT FK_220C7C98A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE accounts ADD CONSTRAINT FK_CAC89EACB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE budgets ADD CONSTRAINT FK_DCAA95489B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE budgets ADD CONSTRAINT FK_DCAA954812469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF34668727ACA70 FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF346687E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invitations ADD CONSTRAINT FK_232710AE9B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4C9B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4C12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE account_users DROP CONSTRAINT FK_220C7C989B6B5FBA');
        $this->addSql('ALTER TABLE account_users DROP CONSTRAINT FK_220C7C98A76ED395');
        $this->addSql('ALTER TABLE accounts DROP CONSTRAINT FK_CAC89EACB03A8386');
        $this->addSql('ALTER TABLE budgets DROP CONSTRAINT FK_DCAA95489B6B5FBA');
        $this->addSql('ALTER TABLE budgets DROP CONSTRAINT FK_DCAA954812469DE2');
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF34668727ACA70');
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF346687E3C61F9');
        $this->addSql('ALTER TABLE invitations DROP CONSTRAINT FK_232710AE9B6B5FBA');
        $this->addSql('ALTER TABLE transactions DROP CONSTRAINT FK_EAA81A4C9B6B5FBA');
        $this->addSql('ALTER TABLE transactions DROP CONSTRAINT FK_EAA81A4C12469DE2');
        $this->addSql('DROP TABLE account_users');
        $this->addSql('DROP TABLE accounts');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP TABLE budgets');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE invitations');
        $this->addSql('DROP TABLE one_time_tokens');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE transactions');
        $this->addSql('DROP TABLE users');
    }
}
